config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :abouts
  resources :adminabouts
  resources :introductions

  resources :caipinclas
  resources :caipins
  resources :admincaipins

  resources :themeclas
  resources :themes
  resources :adminthemes

  resources :promotions
  resources :adminpromotions
  resources :enrolls

  resources :adminenrolls

  resources :admins
  resources :logins

  resources :enters

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/caipin.rb
class Caipin < ActiveRecord::Base
  belongs_to :caipincla
  has_attached_file :caipinimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :caipinimg
end

app/models/caipincla.rb
class Caipincla < ActiveRecord::Base
  has_many :caipins

end

app/models/enroll.rb
class Enroll < ActiveRecord::Base
  belongs_to :promotions
end

app/models/introduction.rb
class Introduction < ActiveRecord::Base
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  has_many :enrolls
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  belongs_to :themecla
  has_attached_file :themeimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :themeimg
end

app/models/themecla.rb
class Themecla < ActiveRecord::Base
  has_many :themes
end

app/controllers/enrolls_controller.rb
class EnrollsController < ApplicationController
  before_action :set_enroll, only: [:show, :edit, :update, :destroy]


  # GET /tests
  # GET /tests.json
  def index
    @enrolls = Enroll.all
    @enroll = Enroll.new
  end

  # GET /tests/1
  # GET /tests/1.json
  def show

  end

  # GET /tests/new
  def new
    @enroll = Enroll.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create

    @enroll = Enroll.new(enroll_params)

    respond_to do |format|

      if @enroll.save

        format.html { redirect_to promotions_path, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @promotion }

      end
    end
  end



  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @enroll.update(enroll_params)
        format.html { redirect_to @enroll, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @enroll }
      else
        format.html { render :edit }
        format.json { render json: @enroll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @enroll.destroy
    respond_to do |format|
      format.html { redirect_to enrolls_path, notice: 'Test was successfully destroyed.' }
      format.json { head :no_enroll }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_enroll
    @enroll = Enroll.find(params[:id])

  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def enroll_params
    params.require(:enroll).permit(:promotion_id, :name,:tel, :content)
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/adminabouts_helper.rb
module AdminaboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/caipinclas_helper.rb
module CaipinclasHelper
end

app/helpers/caipins_helper.rb
module CaipinsHelper
end

app/helpers/enrolls_helper.rb
module EnrollsHelper
end

app/helpers/enters_helper.rb
module EntersHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/themeclas_helper.rb
module ThemeclasHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/enrolls/_formbaomin.html.erb
<%= render 'eform'%>

app/views/enrolls/index.html.erb
<%= render 'adminmenu'%>
<div class="pages">
  <div data-page="projects" class="page no-toolbar no-navbar">
    <div class="page-content">


<script charset="utf-8" src="/editor/kindeditor.js"></script>
<script charset="utf-8" src="/editor/lang/zh-CN.js"></script>

<div id="main">
  <div class="breadcrumb-wrapper">
    <div class="container">
      <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 row ">
        <h3 class="title">报名信息</h3>
        <br>
        <br>
        <table class="table table-striped table-bordered">
          <thead>
          <tr>
            <th>参加报名的活动</th>
            <th>姓名</th>
            <th>电话</th>
            <th>内容</th>
            <th>操作</th>
          </tr>
          </thead>
          <tbody>
          <%@enrolls.each do |f| %>
              <tr>
                <td><%= f.promotion_id %></td>
                <td><%= f.name%></td>
                <td><%= f.tel %></td>
                <td><%= f.content%></td>
                <td><%= f.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
                <td><%= link_to '查看',edit_enrolls_path(f),class:"icon-pencil",'data-no-turbolink' => true %>
                <td><%= link_to '删除',f, method: :delete, data: { confirm: 'Are you sure?' },class:"icon-trash" %></td>
              </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>
    </div>
  </div>
</div>

app/views/enrolls/show.html.erb
<%= @enroll.content %>