config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :abouts
  resources :adminabouts
  resources :introductions

  resources :caipinclas
  resources :caipins
  resources :admincaipins

  resources :themeclas
  resources :themes
  resources :adminthemes

  resources :promotions
  resources :adminpromotions
  resources :enrolls

  resources :adminenrolls

  resources :admins
  resources :logins

  resources :enters

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/caipin.rb
class Caipin < ActiveRecord::Base
  belongs_to :caipincla
  has_attached_file :caipinimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :caipinimg
end

app/models/caipincla.rb
class Caipincla < ActiveRecord::Base
  has_many :caipins

end

app/models/enroll.rb
class Enroll < ActiveRecord::Base
  belongs_to :promotions
end

app/models/introduction.rb
class Introduction < ActiveRecord::Base
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  has_many :enrolls
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  belongs_to :themecla
  has_attached_file :themeimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :themeimg
end

app/models/themecla.rb
class Themecla < ActiveRecord::Base
  has_many :themes
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/caipinclas_helper.rb
module CaipinclasHelper
end

app/helpers/caipins_helper.rb
module CaipinsHelper
end

app/helpers/enrolls_helper.rb
module EnrollsHelper
end

app/helpers/enters_helper.rb
module EntersHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/themeclas_helper.rb
module ThemeclasHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/admins/_form.html.erb
<%= render 'adminmenu'%>
<script language="JavaScript">
    function statusclick() {

        var newcheck= document.getElementById("statuscheck");
        if(newcheck.checked)
        {
            document.getElementById("status").value="1";
        }
        else
        {
            document.getElementById("status").value="0";
        }
    }
</script>











<div class="ibox-content">
  <%= form_for(@admin, :html => {:class=>'form-horizontal m-t',id:"signupForm"}) do |f| %>

      <% @url=request.url %>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">账号：</label>
        <div class="col-sm-5">
          <% if @url.to_s.last(4)!="edit" %>
              <%= f.text_field :user_name ,id:"login",class:"form-control"%>
          <% else %>
              <%= f.text_field :user_name ,id:"login",readonly:"false",class:"form-control"%>
          <% end %>
        </div>
      </div>


      <% if @url.to_s.last(4)!="edit" %>

          <div class="form-group">
            <label class="col-sm-3 control-label">密码：</label>
            <div class="col-sm-5">
              <%= f.password_field :password ,id:"password",class:"form-control"%>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">确认密码：</label>
            <div class="col-sm-5">
              <%= f.password_field :password_confirmation ,class:"form-control"%>
            </div>
          </div>

      <% end %>

<!--      <div class="form-group">
        <label class="col-sm-3 control-label">权限：</label>
        <div class="col-sm-5">
          <= f.text_field :authority ,class:"form-control"%>
        </div>
      </div>


      <div class="form-group">
        <label class="col-sm-3 control-label">激活:</label>
        <div class="col-sm-5">
          <= f.hidden_field :status ,class:"form-control",id:"status",value:"1"%>
          <input type="checkbox" checked value="" id="statuscheck" class="icheckbox" onclick="statusclick()"/>enabled
        </div>
      </div>-->












      <div class="form-group">
        <div class="col-sm-4 col-sm-offset-3">
          <button class="btn btn-sucess" type="submit">提交</button>

        </div>
      </div>

  <% end %>
</div>

app/views/admins/edit.html.erb
<%= render '' %>
<%= render '' %>
<%= render '' %>
<%= render '' %>

app/views/admins/index.html.erb
<%= render 'adminmenu'%>

<div id="main">
  <div class="breadcrumb-wrapper">
    <div class="container">
      <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 row ">
        <h3 class="title">管理员</h3>
        <br>
        <br>
        <table class="table table-hover table-bordered">
          <thead>
          <tr>
            <th>用户名</th>
            <th>账号</th>
            <th>操作</th>
          </tr>
          </thead>
          <tbody>
          <% @admins.each do |admin| %>
              <tr>
                <td>
                  管理员
                </td>
                <td>
                  <%= admin.user_name %>
                </td>
                <td>
                  <%= link_to '编辑',edit_admin_path(admin),class:"icon-pencil",'data-no-turbolink' => true %>&nbsp;
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <br>
      </div>

    </div>
  </div>
</div>

app/views/admins/show.html.erb
<%= render 'form' %>