config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :abouts
  resources :adminabouts
  resources :introductions

  resources :caipinclas
  resources :caipins
  resources :admincaipins

  resources :themeclas
  resources :themes
  resources :adminthemes

  resources :promotions
  resources :adminpromotions
  resources :enrolls

  resources :adminenrolls

  resources :admins
  resources :logins

  resources :enters

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/caipin.rb
class Caipin < ActiveRecord::Base
  belongs_to :caipincla
  has_attached_file :caipinimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :caipinimg
end

app/models/caipincla.rb
class Caipincla < ActiveRecord::Base
  has_many :caipins

end

app/models/enroll.rb
class Enroll < ActiveRecord::Base
  belongs_to :promotions
end

app/models/introduction.rb
class Introduction < ActiveRecord::Base
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  has_many :enrolls
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  belongs_to :themecla
  has_attached_file :themeimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :themeimg
end

app/models/themecla.rb
class Themecla < ActiveRecord::Base
  has_many :themes
end

app/controllers/admincaipins_controller.rb
class AdmincaipinsController < ApplicationController
  before_action :set_caipin, only: [:show, :edit, :update, :destroy]
  def index

    @caipins = Caipin.all
    @caipinclas = Caipincla.all

  end





  def show
    @caipintype = Caipincla.all
  end

  # GET /tests/new
  def new
    @admincaipin = Caipin.new
    @caipintype = Caipincla.all
  end

  # GET /tests/1/edit
  def edit
    @caipintype = Caipincla.all
  end



  # POST /tests
  # POST /tests.json
  def create
    @admincaipin = Caipin.new(caipin_params)

    respond_to do |format|
      if @admincaipin.save
        format.html { redirect_to caipins_path, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @caipin }
      else
        format.html { render :new }
        format.json { render json: @caipin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @caipin.update(caipinq_params)
        format.html { redirect_to @caipin, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @caipin }
      else
        format.html { render :edit }
        format.json { render json: @caipin.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @admincaipin.destroy
    respond_to do |format|
      format.html { redirect_to admincaipins_path, notice: '记录已经删除!' }
      format.json { head :no_content }
    end
  end





  private
  # Use callbacks to share common setup or constraints between actions.
  def set_caipin
    @admincaipin = Caipin.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def caipin_params
    params.require(:caipin).permit(:caipincla_id,:name,:summary,:price,:caipinimg)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admincaipins_helper.rb
module AdmincaipinsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/caipinclas_helper.rb
module CaipinclasHelper
end

app/helpers/caipins_helper.rb
module CaipinsHelper
end

app/helpers/enrolls_helper.rb
module EnrollsHelper
end

app/helpers/enters_helper.rb
module EntersHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/themeclas_helper.rb
module ThemeclasHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/admincaipins/_formcaipin.html.erb
<%= render 'adminmenu'%>
<div class="container">
  <h1>特色菜品</h1>
</div>
<script type="text/javascript" language="JavaScript">

    function get_caipin(){
        document.getElementById("hidden_caipin").value=document.getElementById("select_caipin").value;
    }





</script>
<%= form_for(@admincaipin, :html => {:class=>'form-horizontal m-t',id:"signupForm",:multipart => true}) do |f| %>

    <div class="form-group">
      <label class="col-sm-3 control-label">菜品类型：</label>
      <div class="col-sm-5">
        <%= f.number_field :caipincla_id , class:"form-control",id:"hidden_caipin" %>
        <select class="form-control m-b" id="select_caipin" name="account" onchange="get_caipin()">
          <% @caipintype.each  do |cai| %>
              <option value=<%= cai.id %> ><%=cai.name %></option>

          <% end %>
        </select>
      </div>
    </div>


    <div class="form-group">
      <label class="col-sm-3 control-label">菜品名称：</label>
      <div class="col-sm-5">
        <%= f.text_field :name ,class:"form-control"%>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3 control-label">菜品描述：</label>
      <div class="col-sm-5">
        <%= f.text_field :summary ,class:"form-control"%>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3 control-label">菜品价格：</label>
      <div class="col-sm-5">
        <%= f.text_field :price ,id:"price",class:"form-control"%>
      </div>
    </div>


    <div class="form-group">
      <label class="col-sm-3 control-label">选择图片：</label>
      <div class="col-sm-3">
        <%= f.file_field :caipinimg ,class:"form-control"%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-4 col-sm-offset-3">
        <%= f.submit '提交',class:"button button-glow button-rounded button-raised button-primary pull-right" %>
      </div>
    </div>
    </div>
<% end %>

app/views/admincaipins/edit.html.erb
<%= render 'formcaipin' %>

app/views/admincaipins/index.html.erb
<%= render 'adminmenu'%>
<div class="container">
  <h1>特色菜品</h1>
    <div class="ibox-content">
      <table border="1">
        <thead>
        <tr>
          <th style="text-align:center">菜品类型</th>&nbsp;
          <th style="text-align:center">菜品名称</th>&nbsp;
          <th style="text-align:center">菜品描述</th>&nbsp;
          <th style="text-align:center">菜品价格</th>&nbsp;
          <th style="text-align:center">创建时间</th>&nbsp;
          <th style="text-align:center">操作</th>
        </tr>
        </thead>
        <tbody>
        <% @caipins.each do |f| %>
            <tr>



              <td>
                <% @caipinclas.each do |caipincla| %>
                    <% if caipincla.id  == f.caipincla_id %>
                        <%= caipincla.name %>
                        <% break %>
                    <% end %>
                <% end %>
              </td>
              &nbsp;&nbsp;&nbsp;

              <td style="text-align:center">
                <%= f.name %>
              </td>

              <td style="text-align:center">
                <%= f.summary %>
              </td>

              <td style="text-align:center">
                <%= f.price %>
              </td>





              <td style="text-align:center">
                <%= f.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
              </td>

              <td style="text-align:center">

                <%= link_to "编辑", edit_admincaipin_path(f),class: " external item-link item-content alert-text,fa fa-pencil" %>&nbsp;
                <%= link_to '删除', admincaipin_path(f), class: "fa fa-trash", method: :delete, data: { confirm: 'Are you sure?' } %>
</td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to "新建", new_admincaipin_path,class: "button button-glow button-rounded button-raised button-primary pull-right external item-link item-content alert-text",'data-no-turbolink'=>true %>
      <br>
    </div>

  </div>
</div>

app/views/admincaipins/new.html.erb
<%= render 'formcaipin' %>