config/routes.rb
Rails.application.routes.draw do
  resources :tests
  resources :abouts
  resources :adminabouts
  resources :introductions

  resources :caipinclas
  resources :caipins
  resources :admincaipins

  resources :themeclas
  resources :themes
  resources :adminthemes

  resources :promotions
  resources :adminpromotions
  resources :enrolls

  resources :adminenrolls

  resources :admins
  resources :logins

  resources :enters

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/caipin.rb
class Caipin < ActiveRecord::Base
  belongs_to :caipincla
  has_attached_file :caipinimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :caipinimg
end

app/models/caipincla.rb
class Caipincla < ActiveRecord::Base
  has_many :caipins

end

app/models/enroll.rb
class Enroll < ActiveRecord::Base
  belongs_to :promotions
end

app/models/introduction.rb
class Introduction < ActiveRecord::Base
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  has_many :enrolls
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  belongs_to :themecla
  has_attached_file :themeimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :themeimg
end

app/models/themecla.rb
class Themecla < ActiveRecord::Base
  has_many :themes
end

app/controllers/adminthemes_controller.rb
class AdminthemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]
  def index

    @themes = Theme.all
    @themeclas = Themecla.all

  end





  def show
    @themetype = Themecla.all
  end

  # GET /tests/new
  def new
    @admintheme = Theme.new
    @themetype = Themecla.all

  end

  # GET /tests/1/edit
  def edit
    @themetype = Themecla.all

  end



  # POST /tests
  # POST /tests.json
  def create
    @admintheme= Theme.new(theme_params)

    respond_to do |format|
      if @admintheme.save
        format.html { redirect_to themes_path, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @theme}
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @theme.update(caipinq_params)
        format.html { redirect_to @theme, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @admintheme.destroy
    respond_to do |format|
      format.html { redirect_to adminthemes_path, notice: '记录已经删除!' }
      format.json { head :no_content }
    end
  end





  private
  # Use callbacks to share common setup or constraints between actions.
  def set_theme
    @admintheme = Theme.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def theme_params
    params.require(:theme).permit(:themecla_id,:title,:themeimg)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/adminthemes_helper.rb
module AdminthemesHelper
end

app/helpers/caipinclas_helper.rb
module CaipinclasHelper
end

app/helpers/caipins_helper.rb
module CaipinsHelper
end

app/helpers/enrolls_helper.rb
module EnrollsHelper
end

app/helpers/enters_helper.rb
module EntersHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/themeclas_helper.rb
module ThemeclasHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/adminthemes/_formtheme.html.erb
<%= render 'adminmenu'%>
<div class="container">

  <h1>主题活动</h1>
</div>
<script type="text/javascript" language="JavaScript">

    function get_theme(){
        document.getElementById("hidden_theme").value=document.getElementById("select_theme").value;
    }

    $(document).ready(function () {


        var a = document.getElementById("select_theme");
        a.options[0].selected = true;
        document.getElementById("hidden_theme").value=document.getElementById("select_theme").value;



    });



</script>
<%= form_for(@admintheme, :html => {:class=>'form-horizontal m-t',id:"signupForm",:multipart => true}) do |f| %>

    <div class="form-group">
      <label class="col-sm-3 control-label">活动类型：</label>
      <div class="col-sm-5">
        <%= f.number_field :themecla_id , class:"form-control",id:"hidden_theme" %>
        <select class="form-control m-b" id="select_theme" name="account" onchange="get_theme()">
          <% @themetype.each  do |theme| %>
              <option value=<%= theme.id %> ><%=theme.name %></option>

          <% end %>
        </select>
      </div>
    </div>


    <div class="form-group">
      <label class="col-sm-3 control-label">活动名称：</label>
      <div class="col-sm-5">
        <%= f.text_field :title ,class:"form-control"%>
      </div>
    </div>



    <div class="form-group">
      <label class="col-sm-3 control-label">选择图片：</label>
      <div class="col-sm-3">
        <%= f.file_field :themeimg ,class:"form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-4 col-sm-offset-3">
        <%= f.submit '提交',class:"button button-glow button-rounded button-raised button-primary pull-right" %>
      </div>
    </div>
    </div>
<% end %>

app/views/adminthemes/edit.html.erb
<%= render 'formtheme' %>

app/views/adminthemes/index.html.erb
<%= render 'adminmenu'%>
<div class="container">
  <h1>主题活动</h1>

    <div class="ibox-content">

      <table border="1">
        <thead>
        <tr>
          <th style="text-align:center">活动类型</th>&nbsp;
          <th style="text-align:center">活动标题</th>
          <th style="text-align:center">创建时间</th>
          <th style="text-align:center">操作</th>






        </tr>
        </thead>
        <tbody>
        <% @themes.each do |f| %>
            <tr>



              <td>
                <% @themeclas.each do |themecla| %>
                    <% if themecla.id  == f.themecla_id %>
                        <%= themecla.name %>
                        <% break %>
                    <% end %>
                <% end %>
              </td>


              <td style="text-align:center">
                <%= f.title %>
              </td>




              <td style="text-align:center">
                <%= f.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
              </td>

              <td style="text-align:center">

                <%= link_to "编辑", edit_admintheme_path(f),class: " external item-link item-content alert-text,fa fa-pencil" %>&nbsp;
                <%= link_to '删除', admintheme_path(f), class: "fa fa-trash", method: :delete, data: { confirm: 'Are you sure?' } %>
</td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to "新建", new_admintheme_path,class: "button button-glow button-rounded button-raised button-primary pull-right external item-link item-content alert-text",'data-no-turbolink'=>true %>
      <br>
    </div>

  </div>
</div>

app/views/adminthemes/new.html.erb
<%= render 'formtheme' %>